apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: dataplatform
