apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-{{ts_nodash|replace("T", "")}}
spec:
  type: Python
  sparkVersion: 3.5.0
  mode: cluster
  image: '{{dag_run.conf["airgap_registry_url"]|default("", True)}}gcr.io/mapr-252711/spark-3.5.0:v3.5.0.3.4'
  imagePullPolicy: Always
  imagePullSecrets:
  - imagepull
  mainApplicationFile: "local:///mnt/shared/ezua-tutorials/current-release/Data-Analytics/Spark/pi/pi.py"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.0
  executor:
    cores: 1
    instances: 2
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.0
